In [1]:
# Based on https://deshanadesai.github.io/notes/Fancy-PCA-with-Scikit-Image
import numpy as np
import matplotlib.pyplot as plt
from skimage import io,transform
from PIL import Image
import scipy.misc
%matplotlib inline


def data_aug(img):
	mu = 0
	sigma = 0.1
	feature_vec=np.matrix(evecs_mat)

	# 3 x 1 scaled eigenvalue matrix
	se = np.zeros((3,1))
	se[0][0] = np.random.normal(mu, sigma)*evals[0]
	se[1][0] = np.random.normal(mu, sigma)*evals[1]
	se[2][0] = np.random.normal(mu, sigma)*evals[2]
	se = np.matrix(se)
	val = feature_vec*se

	# Parse through every pixel value.
	for i in xrange(img.shape[0]):
		for j in xrange(img.shape[1]):
			# Parse through every dimension.
			for k in xrange(img.shape[2]):
				img[i,j,k] = float(img[i,j,k]) + float(val[k])
    

#load list of images from txt file
datalist = []
with open("datalist.txt","r") as file:
     for line in file: 
        line = line.strip() 
        datalist.append(line) 
          
#get images from datalist
imlist = (io.imread_collection(datalist))

res = np.zeros(shape=(1,3))
for i in range(len(imlist)):
	# re-size all images to 256 x 256 x 3
	m=transform.resize(imlist[i],(324,153,3))
	# re-shape to make list of RGB vectors.
	arr=m.reshape((324*153),3)
	# consolidate RGB vectors of all images
	res = np.concatenate((res,arr),axis=0)
print len(res)
res = np.delete(res, (0), axis=0)
print res.shape

# subtracting the mean from each dimension
m = res.mean(axis = 0)
res = res - m

R = np.cov(res, rowvar=False)
print R

from numpy import linalg as LA
evals, evecs = LA.eigh(R)

idx = np.argsort(evals)[::-1]
evecs = evecs[:,idx]
# sort eigenvectors according to same index

evals = evals[idx]
# select the first 3 eigenvectors (3 is desired dimension
# of rescaled data array)

evecs = evecs[:, :3]

# make a matrix with the three eigenvectors as its columns.
evecs_mat = np.column_stack((evecs))

# carry out the transformation on the data using eigenvectors
# and return the re-scaled data, eigenvalues, and eigenvectors
m = np.dot(evecs.T, res.T).T



for i in range(270, len(imlist)):
    # re-scaling from 0-1
    img = imlist[i]/255.0
    data_aug(img)
    scipy.misc.imsave("PCA_"+datalist[i], img)





18242497
(18242496, 3)
[[ 0.0626632   0.07707413  0.07041224]
 [ 0.07707413  0.10772428  0.10519072]
 [ 0.07041224  0.10519072  0.11591489]]
